[project]
name = "social-amenities"
version = "0.1.0"
description = "Script that finds social amenities near your location"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "geopy>=2.4.1",
    "requests>=2.32.5",
]
